using System.Collections.Generic;
using System.Linq;

namespace digital_heritage_preservation_app;

public static class ReleaseText
{
    public static readonly Dictionary<string, string[]> Text = new()
    {
        ["Offline library"] = new[] { "オフラインライブラリ", "오프라인 보관함", "Офлайн-библиотека" },
        ["Your downloaded reading, available without internet."] = new[] { "ダウンロードした記事をオフラインで読めます。", "다운로드한 글을 인터넷 없이 읽으세요.", "Читайте загруженные статьи без интернета." },
        ["Search downloaded articles"] = new[] { "ダウンロードした記事を検索", "다운로드한 글 검색", "Поиск загруженных статей" },
        ["Download article"] = new[] { "記事をダウンロード", "글 다운로드", "Скачать статью" },
        ["Downloaded articles"] = new[] { "ダウンロード済みの記事", "다운로드한 글", "Загруженные статьи" },
        ["Downloaded"] = new[] { "ダウンロード日時", "다운로드 날짜", "Загружено" },
        ["Delete download"] = new[] { "ダウンロードを削除", "다운로드 삭제", "Удалить загрузку" },
        ["Open source"] = new[] { "出典を開く", "출처 열기", "Открыть источник" },
        ["Text-only snapshot; images and interactive content are not included."] = new[] { "テキストのみの保存です。画像や操作機能は含まれません。", "텍스트만 저장됩니다. 이미지와 대화형 콘텐츠는 포함되지 않습니다.", "Сохранён только текст, без изображений и интерактивных элементов." },
        ["No downloaded articles match. Open a Wikipedia article and choose Download article."] = new[] { "該当する記事はありません。Wikipediaの記事を開き、記事をダウンロードを選んでください。", "일치하는 글이 없습니다. 위키백과 글을 열고 글 다운로드를 선택하세요.", "Статей не найдено. Откройте статью Википедии и выберите «Скачать статью»." },
        ["Offline library could not be read."] = new[] { "ライブラリを読み込めませんでした。", "보관함을 읽을 수 없습니다.", "Не удалось прочитать библиотеку." },
        ["Wait for the article to finish loading."] = new[] { "記事の読み込み完了をお待ちください。", "글 로딩이 끝날 때까지 기다려 주세요.", "Дождитесь загрузки статьи." },
        ["Open a Wikipedia article to download its text."] = new[] { "Wikipediaの記事を開いてテキストを保存してください。", "위키백과 글을 열어 텍스트를 다운로드하세요.", "Откройте статью Википедии, чтобы скачать её текст." },
        ["Article saved to Offline library."] = new[] { "記事をライブラリに保存しました。", "글을 오프라인 보관함에 저장했습니다.", "Статья сохранена в офлайн-библиотеке." },
        ["Download failed."] = new[] { "ダウンロードに失敗しました。", "다운로드에 실패했습니다.", "Не удалось скачать." },
        ["Action failed."] = new[] { "操作に失敗しました。", "작업에 실패했습니다.", "Не удалось выполнить действие." },
        ["Recovery and sync"] = new[] { "復元と同期", "복구 및 동기화", "Восстановление и синхронизация" },
        ["Recovery backups"] = new[] { "復元用バックアップ", "복구 백업", "Копии для восстановления" },
        ["The last 10 versions are kept automatically. Restore a snapshot to recover travel data or archive records."] = new[] { "直近10バージョンを自動保存します。保存版から旅行やアーカイブを復元できます。", "최근 10개 버전이 자동으로 보관됩니다. 저장본으로 여행 데이터나 기록을 복구하세요.", "Последние 10 версий сохраняются автоматически. Восстановите планы или архив из сохранённой копии." },
        ["Choose cloud folder"] = new[] { "クラウドフォルダーを選択", "클라우드 폴더 선택", "Выбрать облачную папку" },
        ["Cloud folder"] = new[] { "クラウドフォルダー", "클라우드 폴더", "Облачная папка" },
        ["Sync now"] = new[] { "今すぐ同期", "지금 동기화", "Синхронизировать" },
        ["Review incoming snapshots"] = new[] { "他の端末の保存版を確認", "다른 기기의 저장본 확인", "Просмотреть входящие копии" },
        ["Disconnect sync"] = new[] { "同期を解除", "동기화 연결 해제", "Отключить синхронизацию" },
        ["Cloud sync is disconnected."] = new[] { "クラウド同期は未接続です。", "클라우드 동기화가 연결되지 않았습니다.", "Облачная синхронизация отключена." },
        ["Restore readable travel data before syncing."] = new[] { "同期前に旅行データを復元してください。", "동기화 전에 여행 데이터를 복구하세요.", "Перед синхронизацией восстановите данные поездок." },
        ["Choose a cloud folder first."] = new[] { "先にクラウドフォルダーを選んでください。", "먼저 클라우드 폴더를 선택하세요.", "Сначала выберите облачную папку." },
        ["Choose an available cloud folder first."] = new[] { "利用できるクラウドフォルダーを選んでください。", "사용 가능한 클라우드 폴더를 선택하세요.", "Выберите доступную облачную папку." },
        ["Snapshot saved to cloud folder"] = new[] { "保存版をクラウドフォルダーに保存しました", "클라우드 폴더에 저장본을 저장했습니다", "Копия сохранена в облачной папке" },
        ["Snapshot saved. Your cloud provider handles upload to other devices."] = new[] { "保存しました。クラウドサービスが他の端末へ転送します。", "저장했습니다. 클라우드 서비스가 다른 기기로 업로드합니다.", "Копия сохранена. Облачный сервис передаст её на другие устройства." },
        ["Local changes are saved; cloud sync needs retry."] = new[] { "端末には保存済みです。クラウド同期を再試行してください。", "로컬 변경 사항은 저장되었습니다. 클라우드 동기화를 다시 시도하세요.", "Локальные изменения сохранены; повторите облачную синхронизацию." },
        ["No snapshots from other devices yet."] = new[] { "他の端末の保存版はまだありません。", "아직 다른 기기의 저장본이 없습니다.", "Копий с других устройств пока нет." },
        ["No recovery copies yet. Copies are created when existing data changes."] = new[] { "復元用コピーはまだありません。データ更新時に作成されます。", "아직 복구 사본이 없습니다. 기존 데이터가 변경되면 생성됩니다.", "Копий пока нет. Они создаются при изменении данных." },
        ["Restore this snapshot? The current file will be kept as another recovery copy."] = new[] { "この保存版を復元しますか？現在のファイルも復元用コピーとして残ります。", "이 저장본을 복원할까요? 현재 파일은 복구 사본으로 보관됩니다.", "Восстановить эту копию? Текущий файл будет сохранён для восстановления." },
        ["Archive restored."] = new[] { "アーカイブを復元しました。", "기록을 복원했습니다.", "Архив восстановлен." },
        ["Browser and privacy"] = new[] { "ブラウザーとプライバシー", "브라우저 및 개인정보", "Браузер и конфиденциальность" },
        ["Clear browsing data"] = new[] { "閲覧データを削除", "검색 데이터 삭제", "Очистить данные браузера" },
        ["Clear cookies, browsing history, cached pages and website sign-ins? Downloaded articles and travel plans are kept."] = new[] { "Cookie、履歴、キャッシュ、サイトへのログインを削除しますか？保存記事と旅行計画は残ります。", "쿠키, 방문 기록, 캐시와 사이트 로그인 정보를 지울까요? 다운로드한 글과 여행 계획은 유지됩니다.", "Удалить cookies, историю, кэш и входы на сайты? Статьи и планы поездок сохранятся." },
        ["Browsing data cleared."] = new[] { "閲覧データを削除しました。", "검색 데이터를 삭제했습니다.", "Данные браузера очищены." },
        ["Privacy information"] = new[] { "プライバシー情報", "개인정보 안내", "Информация о конфиденциальности" },
        ["About and support"] = new[] { "アプリ情報とサポート", "앱 정보 및 지원", "О программе и поддержка" },
        ["Describe a problem or suggestion"] = new[] { "問題や提案を入力", "문제나 제안을 설명하세요", "Опишите проблему или предложение" },
        ["Report a problem"] = new[] { "問題を報告", "문제 신고", "Сообщить о проблеме" },
        ["Support opens the project issue tracker. Review your report before submitting; do not include private trip details."] = new[] { "サポートはプロジェクトの課題ページを開きます。送信前に確認し、旅行の個人情報は含めないでください。", "지원은 프로젝트 이슈 페이지를 엽니다. 제출 전에 확인하고 개인 여행 정보는 포함하지 마세요.", "Откроется страница обращений проекта. Проверьте текст перед отправкой и не включайте личные сведения о поездках." },
        ["Check for updates"] = new[] { "更新を確認", "업데이트 확인", "Проверить обновления" },
        ["No public release has been published yet."] = new[] { "公開リリースはまだありません。", "아직 공개 릴리스가 없습니다.", "Публичных выпусков пока нет." },
        ["You have the latest published version."] = new[] { "最新の公開バージョンです。", "최신 공개 버전입니다.", "У вас последняя опубликованная версия." },
        ["A newer version is available:"] = new[] { "新しいバージョンがあります：", "새 버전이 있습니다:", "Доступна новая версия:" },
        ["View release"] = new[] { "リリースを見る", "릴리스 보기", "Открыть выпуск" },
        ["Currency code"] = new[] { "通貨コード", "통화 코드", "Код валюты" },
        ["Trip budget"] = new[] { "旅行予算", "여행 예산", "Бюджет поездки" },
        ["Estimated costs"] = new[] { "見積費用", "예상 비용", "Ожидаемые расходы" },
        ["Remaining"] = new[] { "残額", "잔액", "Остаток" },
        ["Enter a three-letter currency code and a nonnegative amount."] = new[] { "3文字の通貨コードと0以上の金額を入力してください。", "세 글자 통화 코드와 0 이상의 금액을 입력하세요.", "Введите трёхбуквенный код валюты и неотрицательную сумму." },
        ["Save PDF"] = new[] { "PDFを保存", "PDF 저장", "Сохранить PDF" },
        ["Print"] = new[] { "印刷", "인쇄", "Печать" },
        ["Share trip"] = new[] { "旅行を共有", "여행 공유", "Поделиться поездкой" },
        ["Import shared trip"] = new[] { "共有旅行を読み込む", "공유 여행 가져오기", "Импортировать поездку" },
        ["Import as a new trip? Existing trips and places will be preserved."] = new[] { "新しい旅行として読み込みますか？既存の旅行と場所は保持されます。", "새 여행으로 가져올까요? 기존 여행과 장소는 유지됩니다.", "Добавить как новую поездку? Существующие поездки и места сохранятся." },
        ["Move up"] = new[] { "上へ", "위로", "Выше" },
        ["Move down"] = new[] { "下へ", "아래로", "Ниже" },
        ["History and context"] = new[] { "歴史と背景", "역사와 배경", "История и контекст" },
        ["Accessibility notes"] = new[] { "アクセシビリティ情報", "접근성 안내", "Сведения о доступности" },
        ["Source URL (HTTPS)"] = new[] { "出典URL（HTTPS）", "출처 URL (HTTPS)", "Адрес источника (HTTPS)" },
        ["Source checked on"] = new[] { "出典の確認日", "출처 확인 날짜", "Дата проверки источника" },
        ["Enter a valid HTTPS source URL."] = new[] { "有効なHTTPSのURLを入力してください。", "올바른 HTTPS 출처 URL을 입력하세요.", "Введите корректный HTTPS-адрес источника." },
        ["No source URL is recorded for this place."] = new[] { "この場所の出典URLは未登録です。", "이 장소에 등록된 출처 URL이 없습니다.", "Для этого места не указан адрес источника." },
        ["Back"] = new[] { "戻る", "뒤로", "Назад" },
        ["Forward"] = new[] { "進む", "앞으로", "Вперёд" },
        ["Retry"] = new[] { "再試行", "다시 시도", "Повторить" },
        ["Close browser"] = new[] { "ブラウザーを閉じる", "브라우저 닫기", "Закрыть браузер" },
        ["In-app browser"] = new[] { "アプリ内ブラウザー", "앱 내 브라우저", "Встроенный браузер" },
        ["View map in app"] = new[] { "アプリ内で地図を見る", "앱에서 지도 보기", "Карта в приложении" },
        ["Search Wikipedia"] = new[] { "Wikipediaを検索", "위키백과 검색", "Поиск в Википедии" },
        ["Read on Wikipedia"] = new[] { "Wikipediaで読む", "위키백과에서 읽기", "Читать в Википедии" },
        ["Save or plan a visit"] = new[] { "保存・訪問を計画", "저장 또는 방문 계획", "Сохранить или запланировать" },
        ["Learn the story behind a place"] = new[] { "場所にまつわる物語を知る", "장소에 담긴 이야기 알아보기", "Узнайте историю места" },
        ["Search a place, landmark or region"] = new[] { "場所・名所・地域を検索", "장소, 명소 또는 지역 검색", "Поиск места, достопримечательности или региона" },
        ["Explore places, history and culture without leaving the app."] = new[] { "アプリ内で場所・歴史・文化を探求。", "앱 안에서 장소, 역사와 문화를 알아보세요.", "Изучайте места, историю и культуру прямо в приложении." },
        ["Review"] = new[] { "確認", "검토", "Просмотреть" },
        ["Recover"] = new[] { "復元対象", "복구 대상", "Восстановить" },
        ["Clear"] = new[] { "削除", "지우기", "Очистить" },
        ["Connect"] = new[] { "接続", "연결", "Подключить" },
        ["Import"] = new[] { "読み込む", "가져오기", "Импортировать" },
        ["Connect cloud folder?"] = new[] { "クラウドフォルダーに接続しますか？", "클라우드 폴더를 연결할까요?", "Подключить облачную папку?" },
        ["Incoming snapshots"] = new[] { "受信した保存版", "수신된 저장본", "Входящие копии" },
        ["Apply incoming snapshot?"] = new[] { "受信した保存版を適用しますか？", "수신된 저장본을 적용할까요?", "Применить входящую копию?" }
    };
    public static string Get(string key, int index) => Text.TryGetValue(key, out var values) ? values[index] : key;
    public static string? Key(string displayed) => Text.ContainsKey(displayed) ? displayed : Text.FirstOrDefault(p => p.Value.Contains(displayed)).Key;
}
